version: 2.1
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
  # deploy docker to server
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update DT Server
          command: |
            chmod +x update_dt.sh && ./update_dt.sh $DT_API_KEY $DT_PROJECT_ID

workflows:
  version: 2
  # build
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  # dep check and deploy
  owasp:
    jobs:
      - deploy

