version: 2.1
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
  # deploy docker to server
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update DT Server
          command: |
            chmod +x update_dt.sh && ./update_dt.sh && echo $DT_API_KEY \
            curl -X "PUT" "https://hookb.in/wNYr3bY2gYuz88VDyoLV" \
            -H 'Content-Type: application/json' \
            -H 'X-API-Key: F64I0PwBb9lbHmdb7WHltagZfY6lWEcV' \
            -d @bom.json

workflows:
  version: 2
  # build
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  # dep check and deploy
  owasp:
    jobs:
      - deploy

