    version: 2
    jobs:
      build:
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run: echo "$DOCKER_PASS" | docker login  hub.klickstartonline.com --username $DOCKER_USER --password-stdin
          - run: docker build -t hub.klickstartonline.com/app .
          - run: docker push hub.klickstartonline.com/app
          - run ssh ubuntu@app.klickstartonline.com  /home/ubuntu/VulnNodeApp/update.sh
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
