version: 2.1
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker

  # SAST on fortify instance
  deploy:       
      - run:
          name: Scan Over SSH on fortify instance
          command: |
            ssh ubuntu@ec2-3-236-145-132.compute-1.amazonaws.com "./scan_node_app.sh"
            
