version: 2.1
jobs:
  build-and-test:
    docker:
      image: circleci/buildpack-deps
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login  hub.klickstartonline.com --username $DOCKER_USER --password-stdin
      - run: docker build -t hub.klickstartonline.com/app .
      - run: docker push hub.klickstartonline.com/app
workflows:
    build-and-test:
      jobs:
        - build-and-test
        
