version: 2.1
jobs:
  # deploy docker to server
  SAST:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: ssh-keyscan ec2-3-236-145-132.compute-1.amazonaws.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "35:3d:de:3b:8c:0f:a8:e9:25:6c:b0:52:6f:22:dc:38"
      - run:
          name: SAST test on ssh with Fortify
          command: |
            ssh ubuntu@ec2-3-236-145-132.compute-1.amazonaws.com "./scan_node_app.sh"

workflows:
  version: 2
  # dependency track before deploy
  sast-fortify:
    jobs:
      - SAST
