version: 2.1
orbs:
  node: circleci/node@1.1.6
  sonarqube: clicklogiq/sonarqube@0.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      # setup env for sonarqube
      - run:
          name: Setup environment
          command: |
            apk update
            apk add --no-cache zip openjdk11-jre-headless
      # install sonarqube scanners
      - run:
          name: Install Sonarqube scanner
          command: >
            wget
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-<<
            parameters.engine_version >>.zip
            unzip sonar-scanner-cli-<< parameters.engine_version >>.zip
workflows:
    build-and-test:
      jobs:
        - build-and-test
        
