version: 2.1
orbs:
  owasp: entur/owasp@0.0.10
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login  hub.klickstartonline.com --username $DOCKER_USER --password-stdin
      - run: docker build -t hub.klickstartonline.com/app .
  # deploy docker to server
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login  hub.klickstartonline.com --username $DOCKER_USER --password-stdin
      - run: docker push hub.klickstartonline.com/app
      - run: ssh-keyscan app.klickstartonline.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@app.klickstartonline.com  "/home/ubuntu/VulnNodeApp/update.sh"
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  deploy-master:
    jobs:
      - deploy
  # owasp:
  #   jobs:
  #     - owasp/commandline_owasp_dependency_check:
  #         arguments: >-
  #           --scan ./ --failOnCVSS 3
