version: 2.1
jobs:
  # SAST using fortify
  SAST:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run: ssh-keyscan ec2-3-236-145-132.compute-1.amazonaws.com >> ~/.ssh/known_hosts
      - run:
          name: SAST over ssh with Fortify instance
          command: |
            ssh ubuntu@ec2-3-236-145-132.compute-1.amazonaws.com "./scan_node_app.sh"

workflows:
  version: 2
  # SAST job
  sast-fortify:
    jobs:
      - SAST
