version: 2.1
orbs:
  node: circleci/node@1.1.6
  sonarqube: clicklogiq/sonarqube@0.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: echo "$DOCKER_PASS" | docker login  hub.klickstartonline.com --username $DOCKER_USER --password-stdin
            - run: docker build -t company/app: .
            - run: docker push company/app
#       - run:
#         name: Build docker image and publish to Private Hub
#         command: |
#           apt update
#           apt add --no-cache zip openjdk11-jre-headless
      # install sonarqube scanners
      #- sonarqube/install-engine
workflows:
    build-and-test:
      jobs:
        - build-and-test
        
