version: 2.1
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
  # deploy docker to server
  SAST:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: SAST test on ssh with Fortify
          command: |
            ssh ubuntu@ec2-3-236-145-132.compute-1.amazonaws.com "./scan_node_app.sh"

workflows:
  version: 2
  # build
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  # dependency track before deploy
  owasp:
    jobs:
      - SAST

