version: 2.1
jobs:
  # build app in docker
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
  # deploy docker to server
  dep-track:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # this JSON file contains .....
          name: Prepare JSON File 
          command: |
            chmod +x update_dt.sh && ./update_dt.sh
      - run: 
          name: Send JSON to OWASP dependency track server
          command: | 
            curl -X "PUT" "http://dt.klickstartonline.com:8080/api/v1/bom" -H "Content-Type: application/json" -H "X-API-Key: $DT_API_KEY" -d @bom.json

workflows:
  version: 2
  # build
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  # dependency track before deploy
  owasp:
    jobs:
      - dep-track

